// .a — `NavigationMeta`:
//
// Metadata for a single navigation property on a
// `@Table` entity. Represents a FK relationship
// from a field on this entity to a target entity.
//
// Example (generated by the codegen):
// ```dart
// // User code:
// @Table
// class Order extends Record {
// @ForeignKey(table: 'customers', column: 'id')
// late int customerId;
//
// late String status;
// }
//
// // Generated EntityMeta gets:
// EntityMeta(
// tableName: 'orders',
// columns: [ColumnMeta(dartField: 'id', ...), ...],
// navigations: [
// NavigationMeta(
// name: 'customer', // ← getter name
// fkColumn: 'customerId', // ← FK on this entity
// targetTable: 'customers', // ← target
// targetColumn: 'id', // ← PK on target
// targetDartType: Customer, // ← for type lookup
// isCollection: false, // 1:1 by default
//),
//],
// ...
//);
// ```
//
// The runtime uses this list to:
// 1. Generate the `customer` getter on the entity
// (.b)
// 2. Translate `o.customer.name` in a closure to a
// JOIN (.c–d)
// 3. Implement `.include_((o) => o.customer)` for
// eager loading (.e)
// 4. Detect N+1 patterns (.f, lint rule)

import 'column_meta.dart';

/// .a: metadata for a single navigation
/// property. Constructed by the codegen and read by
/// the runtime; the runtime never constructs one
/// itself.
class NavigationMeta {
  /// The name of the navigation getter on the entity
  /// (e.g. `'customer'` on Order). Conventionally the
  /// camelCase form of the target table name (e.g.
  /// `'customers'` → `'customer'` for 1:1, `'lineItems'`
  /// for 1:many).
  final String name;

  /// The Dart field name on the source entity that
  /// holds the FK (e.g. `'customerId'` on Order).
  final String fkColumn;

  /// The name of the target table (snake_case, e.g.
  /// `'customers'`).
  final String targetTable;

  /// The name of the target column (snake_case, e.g.
  /// `'id'`).
  final String targetColumn;

  /// The Dart runtime type of the target entity
  /// (e.g. `Customer`).
  final Type targetDartType;

  /// Whether this navigation is 1:1 (single related
  /// entity) or 1:many (list of related entities).
  /// Determined by the codegen based on the inverse
  /// side: if a related entity has a FK back to this
  /// one, it's a 1:many; otherwise 1:1.
  final bool isCollection;

  /// Optional: for 1:many navigations, the name of
  /// the FK field on the target entity that
  /// points back to this one (e.g. for
  /// `Order.lineItems`, the target LineItem has
  /// `orderId`). `null` for 1:1.
  final String? reverseFkColumn;

  /// The source [ColumnMeta] for [fkColumn]. Resolved
  /// by the codegen (it walks the entity's columns to
  /// find the matching one). `null` if not resolvable.
  final ColumnMeta? fkColumnMeta;

  const NavigationMeta({
    required this.name,
    required this.fkColumn,
    required this.targetTable,
    required this.targetColumn,
    required this.targetDartType,
    this.isCollection = false,
    this.reverseFkColumn,
    this.fkColumnMeta,
  });
}
