/// The `Record` base class — a `RecordLike` whose `readField` is
/// satisfied by a runtime registry populated by codegen.
///
/// The codegen in `package:d_rocket_builder` discovers any class
/// that `extends Record` (no annotation required) and emits a
/// registration snippet into the corresponding `part` file. The
/// developer calls the generated `registerAll` once at
/// application startup (e.g., in `main`) to register all the
/// fields at once.
///
/// Example:
///
/// ```dart
/// import 'package:d_rocket/d_rocket.dart';
///
/// part 'author.g.dart';
///
/// class Author extends Record {
/// Author({required this.id, required this.name, required this.country});
/// final int id;
/// final String name;
/// final String country;
/// }
///
/// void main {
/// registerAll; // Register all `extends Record` classes in
/// // this file. Generated by d_rocket_builder.
/// // ... rest of app
/// }
/// ```
///
/// ## Why no annotation is required
///
/// The codegen walks the file and looks for `class X extends
/// Record`. If found, it generates a `_`<X>`RecordInit` const that
/// registers the field accessors with the global
/// registry. A top-level `registerAll` calls each const's
/// constructor to trigger the registration.
///
/// ## Failure mode
///
/// If `registerAll` is not called before the first
/// `MemberAccess.dispatch` on a `Record` subclass, the registry
/// returns `null` for that field (matching the C# LINQ semantics
/// of accessing an undefined field on a dynamic). To catch this
/// earlier, the `Record` base class's constructor checks the
/// registry and throws a `StateError` with a clear message if
/// the concrete class was not registered.
library;

import 'expr.dart';

/// Base class for `RecordLike` types whose field accessors are
/// registered at startup by codegen.
///
/// The user extends this class to make their model a `RecordLike`:
///
/// ```dart
/// class Author extends Record { ... }
/// ```
///
/// The codegen in `package:d_rocket_builder` discovers the class
/// by `extends Record` and generates a registration snippet
/// (no annotation required).
abstract class Record implements RecordLike {
  Record() {
    // Check at construction time that the concrete subclass has
    // been registered. Throws a clear error if not.
    if (!_RecordRegistry.isRegistered(runtimeType)) {
      throw StateError(
        'Class $runtimeType extends Record but has not been '
        'registered. Did you call the generated '
        '`registerAll()` in main()? '
        'See the d_rocket_builder README for the workflow.',
      );
    }
  }

  @override
  Object? readField(String fieldName) {
    return _RecordRegistry.read(this, fieldName);
  }

  /// A debug-friendly `toString` powered by the registry.
  ///
  /// Subclasses inherit this and get a representation like
  /// `Book(id: 1, title: A Wizard of Earthsea, authorId: 1, ...)`
  /// "for free", without having to override `toString` by hand.
  ///
  /// If the subclass has not been registered (i.e. `registerAll`
  /// was not called), falls back to `ClassName` so we don't
  /// crash while debugging.
  @override
  String toString() {
    final fields = _RecordRegistry.allFields(runtimeType);
    if (fields == null) return '$runtimeType()';
    final parts = <String>[];
    fields.forEach((name, accessor) {
      parts.add('$name: ${accessor(this)}');
    });
    return '$runtimeType(${parts.join(', ')})';
  }

  /// Public API for codegen: registers the field accessors for a
  /// [Record] subclass. Called by the `d_rocket_builder`-generated
  /// `_<ClassName>Init` constructor at startup.
  ///
  /// The [fields] map is keyed by field name; the value is a
  /// function that takes an instance of `T` and returns the field
  /// value.
  // ignore: unused_element
  static void register<T>(Map<String, Object? Function(T)> fields) {
    _RecordRegistry.register(fields);
  }
}

/// Internal registry of `Record` subclass field accessors.
///
/// Populated by the codegen-generated `_$<ClassName>RecordInit`
/// consts when `_$registerAll` is called. Not part of the public
/// API — the codegen references it via the private name.
class _RecordRegistry {
  /// Map from `runtimeType` → `fieldName` → field accessor.
  static final Map<Type, Map<String, Object? Function(Object)>> _registry = {};

  /// Registers the field accessors for a class.
  ///
  /// Called by the codegen-generated `_<ClassName>Init`
  /// constructor at startup. The analyzer sees this as unused
  /// because the callsite lives in codegen output (the user's
  /// `*.g.dart` part file), not in d_rocket itself.
  // ignore: unused_element
  static void register<T>(Map<String, Object? Function(T)> fields) {
    _registry[T] = <String, Object? Function(Object)>{
      for (final entry in fields.entries)
        entry.key: (Object obj) {
          return entry.value(obj as T);
        },
    };
  }

  /// Reads a field from [obj] by name. Returns `null` if the
  /// class is not registered or the field is not in the map.
  static Object? read(Object obj, String fieldName) {
    final fields = _registry[obj.runtimeType];
    if (fields == null) return null;
    final accessor = fields[fieldName];
    if (accessor == null) return null;
    return accessor(obj);
  }

  /// Returns the field map for [type], or `null` if [type] has
  /// not been registered. Used by `Record.toString` to produce a
  /// debug-friendly representation.
  static Map<String, Object? Function(Object)>? allFields(Type type) {
    return _registry[type];
  }

  /// Whether the given [type] has been registered.
  static bool isRegistered(Type type) => _registry.containsKey(type);
}
